GET http://localhost:3000/blocks

###

POST http://localhost:5000/blocks
Content-Type: application/json

{
  "data": "ddd BLOCK"
}

###

POST http://localhost:5000/peers
Content-Type: application/json

{
  "peer": "ws://localhost:4000"
}